### ISSUE TITLE
Currency Symbol

### ISSUE THREAD

**Issue by Martin1973X** [malnvenshorn/OctoPrint-FilamentManager#11]
Not everyone uses Euros, it would be nice to have the option to change it depending on locale.

**Comment by malnvenshorn** [comment]
You can change the currency symbol in the settings.

**Comment by bj0** [comment]
I don't see this anywhere in the settings, is another plugin required?

**Comment by malnvenshorn** [comment]
In the top right corner is a button for the plugin configuration. In the dialog which opens can you customize the symbol.
