### ISSUE TITLE
[Question] Ability to start print prior to completion of anlysis?

### ISSUE THREAD

**Issue by TheEagle13** [malnvenshorn/OctoPrint-FilamentManager#115]
Sometimes really large gcode files take forever for analysis happen. Is it possible to make an option to start printing before the analysis is complete? Will Filament manager be able to still correctly subtract usage if you start printing before the analysis completes?

**Comment by malnvenshorn** [comment]
You can start the print before the analysis process has finished. But you may have to disable the verification dialog for the selected spool.

**Comment by TheEagle13** [comment]
Perfect! Thank you!
