### ISSUE TITLE
Remaining weight/percent in sidebar

### ISSUE THREAD

**Issue by Brekel** [malnvenshorn/OctoPrint-FilamentManager#12]
First of all I love this plugin, really really usefull!

I have a small suggestion though. :)

The selection on the sidebar is really nice but it would be even more useful if it would also list the remaining weight/percentage of the selected spool.
Would make for a handy lookup when slicing a file to see if it would work with the remaining filament instead of diving into the settings for example.

**Comment by malnvenshorn** [comment]
The selection already shows the remaining filament on each spool.

**Comment by Brekel** [comment]
Ooops sorry, must've slipped by me since I'm printing and the selection only has a certain width when not active.
