### ISSUE TITLE
Filament Manager won't deduct if the SQL server restarts/looses connection mid print. 

### ISSUE THREAD

**Issue by JamesVexica** [malnvenshorn/OctoPrint-FilamentManager#121]
It seems that Filament Manager won't deduct from the spool when a print has finished if somewhere in between the print the SQL server is restarted. 

#### What were you doing?

Running a print with a set of filament selected. When I had to restart the server containing the SQL database 5 hours before print finished. 

#### What did you expect to happen?
The print, when finished, would deduct the total amount of filament used. 

#### What happened instead?
The plugin didn't take anything from the spool that was selected. 

#### Link to octoprint.log

[Always include the log file.]

https://drive.google.com/open?id=1HJ73-mlwGd3f9BgoUgm89RsUnKAShyVG

#### Link to contents of Javascript console in the browser

[If you're reporting UI issues always include the output of the javascript console of your browser. Always include if unsure.]

#### Further information

[If you have more information which could help me to understand/fix the issue feel free to add them here.]

I have read the FAQ and provided all required information.

**Comment by malnvenshorn** [comment]
I'm aware of this issue. I'm closing this, because there is already a ticket for this (#108).
