### ISSUE TITLE
[Question] Temperature Offset?

### ISSUE THREAD

**Issue by snupple** [malnvenshorn/OctoPrint-FilamentManager#126]
How does the temperature offset work?

Is it supposed to actually effect the printers hotend temp when printing or is it purely a 'note/reminder'  to manually adjust the temperature?

**Comment by malnvenshorn** [comment]
It automatically sets the temperature offset in OctoPrint (the same setting you can also adjust manually). Therefore it affects the hotend temperature.

**Comment by tcurdt** [comment]
Why would the temperature offset need to be different per spool?

**Comment by snupple** [comment]
Not per spool, but per colour or material

**Comment by malnvenshorn** [comment]
I guess this question is answered => closing
