### ISSUE TITLE
Remote Database Initialization Error

### ISSUE THREAD

**Issue by bleem313** [malnvenshorn/OctoPrint-FilamentManager#134]
#### What were you doing?

After setting up a remote database, every time the server starts the plugin throws an error. Everything appears to still work correctly. I am able to add and remove rolls. However, I don't know if some of the functionality is broken because of it.

#### What did you expect to happen?

The server to start without the plugin manager throwing an error.

#### What happened instead?

The plugin throws an sql error stating it failed to initialize the database.

#### Link to octoprint.log

[octoprint.log](https://drive.google.com/open?id=172yUXlcHKN5sJ0BaHpYViEAD9o3E6uRw)

#### Link to gcode file

N/A

#### Link to contents of Javascript console in the browser

N/A

#### Further information

I have read the FAQ and provided all required information.

**Comment by malnvenshorn** [comment]
You need at least PostgreSQL 9.5 as stated in the README.

Duplicate of #96

**Comment by bleem313** [comment]
That fixed it. Thank you for the quick reply. I forgot that the server I'm on is an older server, and didn't think to check version numbers.
