### ISSUE TITLE
[question] mysql server on NAS

### ISSUE THREAD

**Issue by dogson3006** [malnvenshorn/OctoPrint-FilamentManager#135]
hi there,
i´ve got a second printer and a second raspberry pi.
so my idea is to share the database for both raspi´s.
but i won´t install a postgresql on one of these raspi, because i have a NAS running a mysql 5 server.
so, it is possible to share the database above my NAS? and if the answer is yes, how will i do this?

thanks 4 help
volker

**Comment by malnvenshorn** [comment]
Only PostgreSql is supported, because MySql lacks the support to notify clients about database changes.

**Comment by dogson3006** [comment]
i´m sad to hear this. 
but can you please tell me how to install pstgresql on my raspberry pi 3+ running the image from octopi on it?
only typing pip install psycopg2 over putty doesn´t work
thxx

**Comment by malnvenshorn** [comment]
I don't use OctoPi. You can find a guide for Arch Linux in the wiki.

**Comment by dogson3006** [comment]
thank you for answering
