### ISSUE TITLE
[Request] postgresql for raspbian

### ISSUE THREAD

**Issue by moveslikeyoda** [malnvenshorn/OctoPrint-FilamentManager#140]
Could you expand on the postgresql setup instructions to include Raspbian Stretch?  I have tried to piece together on how to do this between your instructions and 3rd part instructions, but am unable to get octoprint to connect to my created DB.

**Comment by malnvenshorn** [comment]
Added a [guide](https://github.com/malnvenshorn/OctoPrint-FilamentManager/wiki/Setup-PostgreSQL-on-Raspbian-\(Stretch\)) for Raspbian to the wiki
