### ISSUE TITLE
Error: Heating failed, system stopped! Heater_ID: 0

### ISSUE THREAD

**Issue by mister2212** [malnvenshorn/OctoPrint-FilamentManager#148]
wenn das plugin installiert ist bekomme ich beim aufheizen einen fehler wegen der hotend temperatur die dann plötzlich aus irgendwelchen gründen auf über 400 Grad aufheizen will. sobald ich das plugin deinstalliere geht alles ganz normal. 
[octoprint.log](https://github.com/malnvenshorn/OctoPrint-FilamentManager/files/2922028/octoprint.log)

**Comment by malnvenshorn** [comment]
Bitte nutze das template. Du kannst es gerne auch auf deutsch ausfüllen, aber **vollständig**.

**Comment by mister2212** [comment]
verstehe leider nicht was ich noch ausfüllen soll. habe den fehler beschrieben und den log angefügt.
