### ISSUE TITLE
Printing from API

### ISSUE THREAD

**Issue by G-Pereira** [malnvenshorn/OctoPrint-FilamentManager#150]
When printing from the api the filament selection is not enforced.

**Comment by malnvenshorn** [comment]
Sorry, but I don't see the issue.

**Comment by G-Pereira** [comment]
It's not an issue neither a feature request. It's an improvement.
When printing from the API (let's say slic3r) it's not possible to block the printing start until the filament is confirmed.

**Comment by malnvenshorn** [comment]
An API is not an user interface. If you use the API to control your prints you have to do the check yourself.
