### ISSUE TITLE
Add support for forgetful operator - started print with wrong filament selected.

### ISSUE THREAD

**Issue by trv-in-3d** [malnvenshorn/OctoPrint-FilamentManager#156]
**Is your feature request related to a problem? Please describe.**
Problem:  even though I moved the Filament Manger to be right next to the PRINT button in Octoprint, I frequently forget to select the correct filament before starting the print. 

**Describe the solution you'd like**
I'd like to make correcting this oversight easier.  I can think of several options:
1)  Allow me to change the selected filament during a print.   it could prompt to ask if it should reset back to start of print, or allow filament change from this point in the print (This would be great for manual filament color changes).
2)  If (1) is not possible, maybe Filament Manager could have a PROMPT BEFORE PRINT option.  If enabled, after PRINT is selected in Octoprint, Filament Manager would pop up a window to either confirm current filament or potentially allow me to select from the filament list.  If disabled (default) Filament Manager would function as it currently does.
 3)  Last choice - at end of print, could filament manager just display or log the total filament consumed?  With this info I could go back and manually adjust quantities from the incorrectly consumed spool and decrement the correct spool.

**Describe alternatives you've considered**
See options above.

**Additional context**
None.

**Comment by malnvenshorn** [comment]
You can already enable a confirmation dialog which asks you to confirm your selected spools before the print. For (3) see #147
