### ISSUE TITLE
Connection fail please help (pgadmin4 and psycopg2 connect script works)

### ISSUE THREAD

**Issue by plug-it-in** [malnvenshorn/OctoPrint-FilamentManager#159]
**Describe the bug**
When I press the Test Connection button for the external database connection it turns red. I can connect to the database as per your setup in postgresql with both pgadmin4 from my Windows machine to the Raspbertry PI OctoPrint, and using a simple script (see screen shot below) connects to postgresql database fine as well.

**Expected behavior**
Button to turn green

**Did the same happen when all other 3rd party plugins are disabled?**
Yes

**Log file**
Drag and drop the octoprint.log here.
[octoprint.log](https://github.com/malnvenshorn/OctoPrint-FilamentManager/files/3108295/octoprint.log)
b
**Screenshots**
![2019-04-23_16-13-31](https://user-images.githubusercontent.com/17591144/56594487-d90d7f00-65e4-11e9-946e-ec228c9e8e27.jpg)
![2019-04-23_15-45-50](https://user-images.githubusercontent.com/17591144/56594500-ddd23300-65e4-11e9-8877-d8e55698bba1.jpg)

**Comment by malnvenshorn** [comment]
> 2019-04-23 15:37:05,022 - octoprint.plugins.filamentmanager - ERROR - Failed to initialize database: No module named psycopg2

The `psycopg2` module is missing.

**Comment by plug-it-in** [comment]
I am afraid yoiu didnt read the complete log and fixed on the first error. I saw that and fixed that issue already. Otherwise the tiny iof program would not have worked.

**Comment by plug-it-in** [comment]
How does one reopen an issue ?
