### ISSUE TITLE
Change multiple filament numbering

### ISSUE THREAD

**Issue by sticilface** [malnvenshorn/OctoPrint-FilamentManager#168]
I've just added MMU to my prusa.  The extruders are numbered from 0-4.  Filament manager starts at 1, so II keep selecting the wrong filament!!  Could you add an option to start it at 0?  

Thanks

**Comment by malnvenshorn** [comment]
The numbering for the filament selection begins with 0. Can you make a screenshot?

**Comment by sticilface** [comment]
sorry i meant 1

**Comment by sticilface** [comment]
https://www.dropbox.com/s/9dam1vvel5jxccz/Screenshot%202019-07-07%2014.03.41.png?dl=0

**Comment by sticilface** [comment]
<img width="794" alt="Screenshot 2019-07-07 14 03 41" src="https://user-images.githubusercontent.com/10061736/60768813-1d76ca00-a0c0-11e9-8d2d-fa901e75d231.png">

**Comment by malnvenshorn** [comment]
I won't change that to avoid confusion. OctoPrint counts from 0 therefore the FM too.
