### ISSUE TITLE
On installation, completion dialog says "Install unknown"

### ISSUE THREAD

**Issue by ChrisWeiss** [malnvenshorn/OctoPrint-FilamentManager#173]
When installation is complete, a dialog is displayed indicating such. The text in the dialog says "Install _unknown_".

I'm fairly sure it should say "Install FilamentManager". I'm guessing there's a string missing in metadata somewhere.
<img width="305" alt="Ender_3_OctoPrint__OctoPrint_" src="https://user-images.githubusercontent.com/419818/62823880-3f45ef80-bb4b-11e9-8f1d-2a32ed32187c.png">

**Comment by malnvenshorn** [comment]
This has nothing to do with FM. 

https://community.octoprint.org/t/installing-a-plugin-shows-me-unknown-in-the-popup-i-cant-uninstall-plugins-through-the-plugin-manager-octoprint-up-to-1-3-8-octopi-0-15-0-or-pip-10-x/1746
