### ISSUE TITLE
FilamentManager API usage

### ISSUE THREAD

**Issue by nikee9** [malnvenshorn/OctoPrint-FilamentManager#175]
Just needed some clarification on how to use the FilamentManager API, I can see in the API folder of the source code that there is some request setup such as GET /profiles. 

When I try GET /api/profiles it returns a 404. URL not found.

Could you provide an example similar to how the octoprint API is documented
https://docs.octoprint.org/en/master/api/index.html

**Comment by NotExpectYet** [comment]
Interested in this myself, tried all sorts of combinations

**Comment by malnvenshorn** [comment]
Your URL is wrong, see https://docs.octoprint.org/en/master/plugins/mixins.html#blueprintplugin

For such questions you should got to https://community.octoprint.org/

**Comment by nikee9** [comment]
I see it working now, thanks!

**Comment by s1mpleman** [comment]
Thanks!
