### ISSUE TITLE
Cannot Confirm Selected Spool

### ISSUE THREAD

**Issue by ghost** [malnvenshorn/OctoPrint-FilamentManager#176]
**Describe the bug**
After loading gcode into Octoprint and trying to start the job, I get the "Confirm Selected Spool" dialogue box. Previously, this had been working, and I was able to select my spool from the dropdown and begin the job.
However, now it just says "There are no information available about the active tools for the print job. Make sure the analysing process of the file has finished and that it's loaded correctly." and the "Start Print" button is disabled.

I have confirmed that the gcode has finished being analyzed by Octoprint, as I am able to view all layers through GCode Viewer.

I am able to begin prints if I turn the confirmation dialogue box off, but it does not show cost estimations.

**Steps to reproduce**
See above

**Expected behavior**
I should be able to select a spool to confirm and begin the print job.

**Did the same happen when all other 3rd party plugins are disabled?**
Yes. With only Filament Manager active, the problem still occurs.

**Log file**
[octoprint.log](https://github.com/malnvenshorn/OctoPrint-FilamentManager/files/3660515/octoprint.log)

**Screenshots**
![image](https://user-images.githubusercontent.com/4358525/65735619-0b486e80-e0a6-11e9-8612-58425090a559.png)

**Additional context**

**Comment by malnvenshorn** [comment]
It's not a bug. This feature only works if OctoPrint has finished analyzing the GCode file and that's not the case, e.g the approximated print time is missing.
