### ISSUE TITLE
Support for MariaDB as back end Database

### ISSUE THREAD

**Issue by Snille** [malnvenshorn/OctoPrint-FilamentManager#179]
**Is your feature request related to a problem? Please describe.**
No problem really, just a nice to have feature, it would be nice to be able to use MariaDB as a back end database. I have other systems using my "House-database" that I have on a "database-server". Would be nice to be able to utilize that database for Filament as well. 

**Describe the solution you'd like**
Just a way to select MariaDB as a back end database.

**Describe alternatives you've considered**
I was thinking of installing an instance of PostgreSQL on my database server, but rather not. 

**Additional context**
For the moment I have two Octoprint instances that utilizes the PostgreSQL on the local Raspberry.  But I'm afraid that I'll lose the data if the Pi SD-Card crashes for example. I would rather have the "data" on a safe server. :)

Thank you!

**Comment by malnvenshorn** [comment]
The reason that there is no support for MySQL/MariaDB is that these database systems doesn't have a notification mechanism. There is a request for this on the [MariaDB tracker](https://jira.mariadb.org/browse/MDEV-16590).

**Comment by Snille** [comment]
Ah, I see. Thank you for letting me know. I'll be installing a postgresql along side my Maria then. :) It's not a huge problem, just have to remember to backup them both. :)
