### ISSUE TITLE
Spool select before print

### ISSUE THREAD

**Issue by delonet-ai** [malnvenshorn/OctoPrint-FilamentManager#184]
Dear Sven, could you please add a function to ask user to select or to check spool before print starts.
I always forget to select the right spool before print... =(
It will be great to have such option for some users. 

Thank you for your work!

Wbr, Evgeniy.

**Comment by ruedigernarr** [comment]
@delonet-ai this function already exists (and is quite useful). You can activate it in the plugins settings. It asks you to select the spool form a dropdown and it only works if you select the predefined spool.

**Comment by malnvenshorn** [comment]
Yes therefore I'm closing this :)
