### ISSUE TITLE
Error on Spool select, by using PostgreSQL

### ISSUE THREAD

**Issue by mawi1986** [malnvenshorn/OctoPrint-FilamentManager#192]
Hello
im using the FilamentManager with PostgreSQL on an QNAP-NAS.
I can record the spools etc., they are also written to the database, but as soon as I select a spool for printing in Octoprint, I receive an error message. :-(

Error:
Could not select spool
There was an unexpected error while selecting the spool, please consult the logs.

Error LOG:
2020-01-21 20:54:56,914 - octoprint.plugins.filamentmanager - ERROR - Failed to update selected spool for tool0: (psycopg2.errors.SyntaxError) syntax error at or near "ON"
LINE 1: ...ES (0, '840fdfe6-37c8-11ea-a5ed-b827eb8dc05f', 2) ON CONFLIC...
                                                             ^
 [SQL: 'INSERT INTO selections (tool, client_id, spool_id) VALUES (%(tool)s, %(client_id)s, %(spool_id)s) ON CONFLICT ON CONSTRAINT selections_pkey DO UPDATE SET spool_id = %(param_1)s'] [parameters: {'tool': 0, 'param_1': 2, 'client_id': '840fdfe6-37c8-11ea-a5ed-b827eb8dc05f', 'spool_id': 2}]
2020-01-21 20:54:56,932 - tornado.access - ERROR - 500 PATCH /plugin/filamentmanager/selections/0 (::ffff:192.168.1.28) 51.72ms

what can I do to fix this error message?

**Comment by malnvenshorn** [comment]
Quote from the README

> Support for PostgreSQL (>=9.5) as common database for multiple OctoPrint instances

Because you provided no further information I guess this is your problem.
