### ISSUE TITLE
Shared Data

### ISSUE THREAD

**Issue by KenLucke** [malnvenshorn/OctoPrint-FilamentManager#194]
I cannot find an easy way to leave a feature request, not being that familiar with GitHub, so here goes:

The idea behind this is good, but many of us have multiple printers and multiple iterations of OctoPrint running.  

Unfortunately, this plugin doesn't allow what happens on one OctoPrint to be shared on the other(s). 

 I would like to see some sort of database sharing among the different iterations, so that filament tracking used on one printer is also available on any others.  For starters, it could be just shared if they are on the same local LAN, to avoid having to do any central repository "cloud" BS.  

A master/slave setup where one iteration would save all the data and the others would read and/or modify it would work, backing up the data to their local system in case the master was not available for whatever reason.  When the master reappeared on the network, the master's files would be updated based upon "last saved" usage info.

**Comment by malnvenshorn** [comment]
You can use PostgreSQL as database backend for all your OctoPrint instances => closing.
