### ISSUE TITLE
checkbox in settings - Reset filament choose after job complete

### ISSUE THREAD

**Issue by D1M0N-UA** [malnvenshorn/OctoPrint-FilamentManager#20]

**Comment by malnvenshorn** [comment]
Please provide a use case. I don't see the benefit of that.

**Comment by spaelectronics** [comment]
I've had a few cases where I changed the filament on my printer and forgot to switch it in octoprint. 

I think he's requesting a way to prevent forgetting to choose the correct filament in octoprint.

I would like this feature as well. As I seem to constantly forget to select the correct filament.

**Comment by D1M0N-UA** [comment]
sory my bad english... spaelectronics right

**Comment by spaelectronics** [comment]
Yeah, I'd love to see this feature, so I don't forget to select the correct filament.

**Comment by malnvenshorn** [comment]
I'm closing this because I created a ticked (#36) for this issue. Feel free to add your comments.
