### ISSUE TITLE
Filament Data via REST API

### ISSUE THREAD

**Issue by Tobi0892** [malnvenshorn/OctoPrint-FilamentManager#206]
**Is your feature request related to a problem? Please describe.**
As my printer is located in the basement, I extract various data from octoprint (via the API) and other sensors (DHT22, CCS811 etc via Python) and send it via MQTT to my home assistant instance to be displayed on a tablet:

![image](https://user-images.githubusercontent.com/53291930/80341148-2c528700-8862-11ea-8147-4ef037b799cd.png)

As such, I would love to be able to extract data from the filament manager plugin.

**Describe the solution you'd like**
I would like to extract the name, vendor, material, weight, weight left and weight used % data from the filament manager plugin via the octoprint REST API, i.e. http://octopi/api/filament-manager/

**Describe alternatives you've considered**
As my python data collector runs as a cronjob on the octopi, it could possibly also get the data directly from the database.

**Comment by VibroAxe** [comment]
this already exists! 

http://octoprint/plugin/filamentmanager/spools
