### ISSUE TITLE
Import/Export Of Filament Inventory

### ISSUE THREAD

**Issue by bgoddard79** [malnvenshorn/OctoPrint-FilamentManager#21]
Would it be possible to implement a feature to export your Filament inventory list as a CSV file?

**Comment by stelgenhof** [comment]
I think that would be a very helpful feature. Likewise I think an import feature would be useful as well. If you have a large inventory of filaments (variety of brands, colors, types, etc.) it is quite some work to add them via the UI.

**Comment by malnvenshorn** [comment]
Implemented feature in the develop branch. Feel free to test it out.
