### ISSUE TITLE
Filament List is empty after upgrade to v0.3.0

### ISSUE THREAD

**Issue by stelgenhof** [malnvenshorn/OctoPrint-FilamentManager#22]
After upgrading OctoPrint to version 1.3.5 and Filament Manager to 0.3.0, my list of spools are not visible and OctoPrint just shows a continuous spinner with the dropdown list being empty. Also the list of spools via the Settings menu is empty (See screenshot).

![filament_manager](https://user-images.githubusercontent.com/529544/31640878-f2bdbeec-b31b-11e7-9e54-81c490dc0fa5.png)

**Comment by malnvenshorn** [comment]
Please provide all information as requested in the issue template.

**Comment by stelgenhof** [comment]
Please disregard this issue. After I cleared my browser cache and refreshed the page, the list of filaments are visible. (All is working well)

**Comment by malnvenshorn** [comment]
I reopened this, because maybe people will read this before opening another issue.

**Comment by apazga** [comment]
Thanks @malnvenshorn & @stelgenhof for the solution. I'll try it this afternoon.
Keep up the good work! ^_^

**Comment by malnvenshorn** [comment]
Added FAQ entry in the readme
