### ISSUE TITLE
Update breaks ability for Filament Manager to use external postgresql database

### ISSUE THREAD

**Issue by mpd352** [malnvenshorn/OctoPrint-FilamentManager#228]
Update.  Filament manager still works, only with just the local database.  It can no longer access the external postgresql database.  Your instructions say to run this command:  pip install psycopg2.  That returns an error "command not found"  I'm not familiar enough with this OS to find away around this.

Any suggestions?

Thanks

**Comment by rufinus** [comment]
https://community.octoprint.org/t/filament-manager-plugin-how-to-setup-postgresql-database/10698
