### ISSUE TITLE
Latest version update does not show my previous filament database

### ISSUE THREAD

**Issue by apazga** [malnvenshorn/OctoPrint-FilamentManager#24]
Yesterday I updated to latest version (0.3.0) from (0.2.2).

I have 5-6 filament spools added. After the update, list is empty, and "loading circle" is shown at the top when I tried to list my previously added filaments. I even try adding something new, but it doesn't work.
I tried restarting OctoPrint, but same happened.

I needed to roll back to 0.2.2 via pip --force-install, and everything was fine again.

Octoprint version used (Lastet one: 1.3.5). Just updated it yesterday too.

**Comment by malnvenshorn** [comment]
See #22 and #23

**Comment by apazga** [comment]
Oh, thanks!
