### ISSUE TITLE
Cancelled print still subtracts print requirements from roll

### ISSUE THREAD

**Issue by beercity** [malnvenshorn/OctoPrint-FilamentManager#26]
I cancelled a job right after starting it.  I was using a brand new spool, and filament manager subtracted the requirements for the job from the spool.

I suspect there should be a way to subtract only the used filament from the spool. If it is not possible to do this, at least an estimate based on % of job completed.

I am using the latest Octoprint as well as Filament Manager versions.

**Comment by malnvenshorn** [comment]
It only counts the used filament so this shouldn't be an issue. Please stick to the issue template and provide all information, otherwise I can't help.

**Comment by beercity** [comment]
I have a long print running now but I will get a good test of the scenario once I am able.

**Comment by malnvenshorn** [comment]
Closed due to the lack of information. I will reopen the ticket if you provide ALL required information.
