### ISSUE TITLE
No count of filament with prusa i3 mk2 multicolor

### ISSUE THREAD

**Issue by patrickfanz** [malnvenshorn/OctoPrint-FilamentManager#28]
I have Octoprint version: OctoPrint 1.3.5 (master branch)
Filament Manager: 0.3.0
Printer: prusa i3 mk2 multicolor (4 colors)

Filament-Manger does not count the selected Filament on the main page at, where is written "Tool 0".
After a print is always written the same value of gram.
In the settings I have added all my filaments, but I have to correct the values of rest of the filaments by hand.
![filamentmanager](https://user-images.githubusercontent.com/33087859/31993654-32d4b2e8-b97e-11e7-9d63-324e992947d4.jpg)

**Comment by malnvenshorn** [comment]
Please stick to the issue template and provide all information, otherwise I can't help.

**Comment by malnvenshorn** [comment]
Closed due to the lack of information. I will reopen the ticket if you provide ALL required information.
