### ISSUE TITLE
Support for Multi-Material (Prusa i3MK2S MM)

### ISSUE THREAD

**Issue by mfmjos** [malnvenshorn/OctoPrint-FilamentManager#30]
This is really a feature request. I didn't see a proper place of that type of thing.

#### What were you doing?
Printing objects using multiple filaments

#### What did you expect to happen?
I would like to track multiple filaments in the same print.

#### What happened instead?
Currently it appears that FilamentManager only tracks one spool at a time.

**Comment by malnvenshorn** [comment]
The odometer feature supports multiple extruder. If you encounter issues 
please file in a complete bug report.

**Comment by mfmjos** [comment]
Thank you very much for responding. I didn't have my extruder count set correctly (I just upgraded to 4 materials). Now I see that filament manager does exactly what I need.
