### ISSUE TITLE
[request] Detect changed filament type from gcode and prompt user : has filament changed? 

### ISSUE THREAD

**Issue by sticilface** [malnvenshorn/OctoPrint-FilamentManager#34]
I seem to always forget to change the filament.  
Is it possible to identify from the gcode that the filament/tempsettings have changed and then query the user has it changed and provide a drop down box.

Alternatively have it has a dialog whenever you press print so that you are prompted to change the filament.

**Comment by malnvenshorn** [comment]
It is not possible to detect a filament change.

There is already another ticket (#20) addressing the same issue. But I'm still evaluating the best approach.

**Comment by malnvenshorn** [comment]
I'm closing this because I created a ticked (#36) for this issue. Feel free to add your comments.
