### ISSUE TITLE
Frontend Popup Selection / temp control

### ISSUE THREAD

**Issue by PowerShellCrack** [malnvenshorn/OctoPrint-FilamentManager#4]
I think this plugin is an awesome idea. I currently the print history plugin which allows spool selection, but it doesn't record how much is used and what is left. This plugin would be awesome is I was able to select the spool right before I start the print; instead of going into settings and changing the tool. 

Another added feature to this database would be print temperatures for each spool. Then maybe when  popup message come up prior to finalizing the print queue asking what filament is being used. This could ultimately control the temp settings as well. 

Here is an idea I was thinking of an ran across yours. I also spoke about it here: https://github.com/foosel/OctoPrint/issues/2092. This what I thought the popup could look like: 
![popup](https://lh3.googleusercontent.com/uuBarzsN8dipbQVh8U6ZB3ta1iK9y46BgG7ZYzUXJWk5Yqb5s_p50ZBvVXaWjCXRDFR2K7MkZNn4k67SE6jnWKNCq0RcEHGGYCzWVGp_emwoKGboyEUlk_Gu72L4pOr6R8geGo1M8mgFj37QUNemQfBt_i1iClL9j7DLBjauocmXWAbjtxpBj62JaKXo7JdFzRm7EWci4YOEwK8rCf8v8uvjuPc7E4ibGCakU7kymcbLwcs5LDv5BNrhwaq1-4u_5MsIv0QqaDC2Y85_K0tZ5KFEKK2fV0fMy1xflgXaa9jztP44WT-DNSB8-TsNQIbi3aua6jlDEj-ae1e842PhaGPShP55-hcg0bg-qu4tpDK0AU-pcAV2rlR-TGlSg-rwKM8ILvMUaA2RdG8dJvMF16Vl8J4jxtHl66KfC5qqhsFTqfpmx2OkKpabcNp8-xEjIKv8cCGQMyXeY7M3axRTqlHiGTr2K7zj1rX4Gk8PT8KGumIcshkFsNf3tqlgLQ08sn7K1HtcB0wDy-yUrC-hNEO4digpHymxoNJBLJUtvdTvGwX786tYOkKZQkrwjZtViLInAEnzB0nmmNJyZTCDVu7JUg7S-MeOFfnmzURd62RoYAzFSqBw=w656-h437-no)

**Comment by malnvenshorn** [comment]
> This plugin would be awesome is I was able to select the spool right before I start the print; instead of going into settings and changing the tool.

I know that it seem not very convenient that you have to open the settings to change the selected spools. I thought about adding this to the sidebar, but the selection would be persistent. It gets only saved when you press 'save' in the settings window, because I'm using the 'config.yaml' to store those selections. Maybe I should store it in the database to, but I have to think about it a bit more.

> Another added feature to this database would be print temperatures for each spool. Then maybe when popup message come up prior to finalizing the print queue asking what filament is being used. This could ultimately control the temp settings as well.

I'm not going to implement such a feature, because that's what slicers are for. For different material you need not only the temperature. Flow rate, cooling fan settings, retraction rate, etc. might differ also. To sum it up you have to slice your model again and for this you have the Cura or Slic3r plugin.

**Comment by jasoncross** [comment]
> I'm not going to implement such a feature, because that's what slicers are for. For different material you need not only the temperature. Flow rate, cooling fan settings, retraction rate, etc. might differ also. To sum it up you have to slice your model again and for this you have the Cura or Slic3r plugin.

I disagree.  For the same model in PLA, for example, I almost never re-slice.  Why would I if the only difference is optimal temperature?

**Comment by PowerShellCrack** [comment]
That's what I was saying. I think alot if people don't change their infill retractions, etc that often. Usually oncdbuvgeg it right it's good for most prints. But we are constantly changing filament and temps. I just thought that with the ability to record filament usage, controlling the temp as well would help reduce failed prints. It would be an automated way of helping typical uses.

 Or maybe have a confirmation popup confirming filament spool and print temp. Again this is just a thought. I'm not that good at writing code for the octoprint, but I'm learning. Hopefully when I do, I will write it as my own plugin.

**Comment by jcjenk** [comment]
I think having another column for preferred temperature is a great idea.  It doesn't have to make any changes to the print/slice but it would be a reminder to me on the temp that I had success with.  Why not add another column for "notes" where I could write anything I want about the spool (where I bought it, my thoughts on it, anything to remind me.  I have about 6 different spools I'm using and can't keep it all straight.

**Comment by malnvenshorn** [comment]
In the next version of the plugin you can set a temperature offset for each spool which gets automatically applied on spool selection.

**Comment by jasoncross** [comment]
Excellent. Glad to hear it.
