### ISSUE TITLE
Sidebar icon broken when used in conjunction w/ TouchUI + Enable Customization option turned on

### ISSUE THREAD

**Issue by felixleong** [malnvenshorn/OctoPrint-FilamentManager#41]
#### What were you doing?

Same issue as #25.

However, this time the icon would not appear if TouchUI plugin installed with the "Enable Customization" option enabled.

#### What did you expect to happen?

The sidebar reel icon would appear.

#### What happened instead?

A Unicode square block appears.

#### Link to octoprint.log

Not applicable

#### Link to gcode file

Not applicable

#### Link to contents of Javascript console in the browser

Not applicable

#### Further information

This is mainly due to the fact that, after loading the page, TouchUI has a Javascript function that would replace the touchui CSS w/ touchui.custom.css and causes the new CSS to be appended later and overriding the font option via the `.fa` class.

A suggested fix is to append `!important` to the `.fa-reel` CSS rule to ensure such font override won't occur.

```css
.fa-reel {
  font-family: icomoon !important;
}
```

I have read the FAQ and provided all required information.

**Comment by malnvenshorn** [comment]
Thanks for that. It's not easy for me to discover issues related to plugins I'm not using. I've just pushed the workaround to `develop`.
