### ISSUE TITLE
[Question] Change currency for Price from Euro to Dollar?

### ISSUE THREAD

**Issue by SilverMooseDesigns** [malnvenshorn/OctoPrint-FilamentManager#49]
Thank you Sven for creating this plugin! 
Is it possible to change the Price option from Euro to American Dollar? Is it possible that I could modify the code in order to apply a simple conversion rate. If so, which file would I apply the changes.
Thanks!
Mike

I have read the FAQ and provided all required information.

**Comment by malnvenshorn** [comment]
You can change the currency symbol in the settings.

**Comment by SilverMooseDesigns** [comment]
Thank you very much! It was very easy to change the currency rate in
settings. I overlooked that there was an icon for the Plugin Configuration.
Thanks,
Mike
