### ISSUE TITLE
Wont Install Error Code 1

### ISSUE THREAD

**Issue by Wetts11** [malnvenshorn/OctoPrint-FilamentManager#64]
#### What were you doing?

Trying to install Filament Manager via the Manage Plugin Tab in Octoprint.

#### What did you expect to happen?
Filament Manager to be installed

#### What happened instead?
Error Code 1
#### Link to octoprint.log
[octoprint.log](https://github.com/malnvenshorn/OctoPrint-FilamentManager/files/1592722/octoprint.log)

#### Link to contents of Javascript console in the browser
https://github.com/malnvenshorn/OctoPrint-FilamentManager/wiki#faq

#### Further information

Readout, from Plugin Manager..... "Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-kuytAt/psycopg2/
Error!
Could not parse output from pip, see plugin_pluginmanager_console.log for generated output"

I have read the FAQ and provided all required information.

**Comment by malnvenshorn** [comment]
https://github.com/malnvenshorn/OctoPrint-FilamentManager#setup
