### ISSUE TITLE
No selection of spool

### ISSUE THREAD

**Issue by scharrin2** [malnvenshorn/OctoPrint-FilamentManager#73]
When pressing on "Print" the selection screen for the spool is not shown and the Button "Start Print" is inactive.
When I retry 4 to 5 time the selection for the spool is shown
---

#### What were you doing?

Press on button "Print" (in tho top) or on the Button "Print" above a single file.

#### What did you expect to happen?

The dropdown for the spool should be shown

#### What happened instead?

The dropdown for the Spool is missing

#### Link to octoprint.log

[octoprint.log](https://github.com/malnvenshorn/OctoPrint-FilamentManager/files/1629282/octoprint.log)

#### Link to gcode file

[If you encounter issues with the odometer feature provide a small gcode file which produces the problem.]

#### Link to contents of Javascript console in the browser

[If you're reporting UI issues always include the output of the javascript console of your browser. Always include if unsure.]

#### Further information

![bildschirmfoto 2018-01-14 um 12 24 46](https://user-images.githubusercontent.com/22325491/34915414-8c7dfc90-f926-11e7-8db8-77e99162354a.png)

I have read the FAQ and provided all required information.

**Comment by malnvenshorn** [comment]
Could you please also provide the content of the Javascript console from your browser?

**Comment by scharrin2** [comment]
Hello,

Do you know how to activate on Safari browser on Mac?


Best regards,
Christian

Am 14.01.2018 um 12:51 schrieb Sven Lohrmann <notifications@github.com<mailto:notifications@github.com>>:


Could you please also provide the content of the Javascript console from your browser?

**Comment by malnvenshorn** [comment]
No sorry I don't know that. I also have to say that I'm not supporting the Safari browser because I don't own any apple device and therefore I cannot test with that browser. Maybe you could try it with  a chromium based browser or firefox.

**Comment by scharrin2** [comment]
OK – I will try it with Google Chrome on Mac!


Best regards,
Christian

Von: Sven Lohrmann <notifications@github.com>
Antworten an: malnvenshorn/OctoPrint-FilamentManager <reply@reply.github.com>
Datum: Sonntag, 14. Januar 2018 um 13:19
An: malnvenshorn/OctoPrint-FilamentManager <OctoPrint-FilamentManager@noreply.github.com>
Cc: Christian Scharringer <christian@scharringer.de>, Author <author@noreply.github.com>
Betreff: Re: [malnvenshorn/OctoPrint-FilamentManager] No selection of spool (#73)


No sorry I don't know that. I also have to say that I'm not supporting the Safari browser because I don't own any apple device and therefore I cannot test with that browser. Maybe you could try it with a chromium based browser or firefox.

**Comment by scharrin2** [comment]
Do you mean only the output (screenshot) from the java-script console?

It only looks like this:
![bildschirmfoto 2018-01-14 um 13 54 29](https://user-images.githubusercontent.com/22325491/34916101-7d23fe32-f932-11e7-8c2b-bc02a6bc76a7.png)

**Comment by malnvenshorn** [comment]
Yes that's what I meant. But I cannot see any error.

Because the dialog shows only selections for tools which are actually used by the print job I would explain this behavior with the fact that the analyzing process of the selected file is not finished at the time the dialog opens. This would correspond to the fact that the selection appears after some retries. 

It would be great if you could verify that in your case.

**Comment by TylonHH** [comment]
I had this right now too, but in Firefox.
After some clicks to box was shown. My GCODE was 10MB big/small.
Unfortunately I forget the Java console. But I'll too next time.

**Comment by TylonHH** [comment]
![spool](https://user-images.githubusercontent.com/18073299/35137409-872c00ea-fce9-11e7-944c-c1b5d4a3b158.PNG)

Here is the provided [Link](https://developer.mozilla.org/de/docs/Web/JavaScript/Reference/Fehler/Property_access_denied?utm_campaign=default&utm_medium=firefox-console-errors&utm_source=mozilla) in the Message above

**Comment by TylonHH** [comment]
What I found out. When under "Status" the correct weight and tool is not red or calculated, your pop-up is empty. I had to refresh my browser site and/or load a different file and load the specific file again until the "Status" is correct.
I donno who is responsible for this "Status"

**Comment by malnvenshorn** [comment]
Thanks. I think this confirms my previous speculation. I'm going to revise the dialog so that the user isn't confronted with an empty dialog and don't know why this happened.

**Comment by TylonHH** [comment]
Yeah you're right. But please leave this popup. We should solve the problem why the status isn't updated.

**Comment by sticilface** [comment]
I can confirm that I get this quite frequently too
<img width="701" alt="screenshot 2018-01-24 11 18 40" src="https://user-images.githubusercontent.com/10061736/35329659-96dc3b82-00f8-11e8-83d8-79fab469528b.png">

Hitting refresh on the browser a few times gets rid of it.

**Comment by malnvenshorn** [comment]
@TylonHH the only cases where this should happens are:

* The file is not analysed by OctoPrint yet
* Loading the file takes some time

If this issue appears after the used filament and print time has been updated in the sidebar then we might have a bug somewhere.

**Comment by TylonHH** [comment]
@malnvenshorn you're right. That's what I ment, that someone is responsible.
I'll open an issue at @foosel GitHub.

**Comment by szafran81** [comment]
It would also be nice if after that window shows up with the list of spools to select that the currently selected spool on the main screen would be preselected.

**Comment by malnvenshorn** [comment]
@szafran81 see #71

**Comment by malnvenshorn** [comment]
Added some information to the confirmation dialog if no selection is available to explain the cause of this.

If I get some information that show that there is a bug in the filament manager after all I'll reopen this ticket.

**Comment by jesasi** [comment]
I think it is bug: https://discourse.octoprint.org/t/selecting-problem-in-filamentmanager/

**Comment by TylonHH** [comment]
It's not a bug of the filament manager plugin. Because this plugin don't analyze the gcode.

**Comment by malnvenshorn** [comment]
Unfortunately the video from the linked  post doesn't show whether the file was fully analysed before the dialog was opened or not. Therefore I'm assuming the file was not analysed yet. In this case the behavior is as intended.

**Comment by bartwybouw** [comment]
I have the same issue.
And yes the file was fully analysed.
I can select certain spools and get the start button active, others I cannot (of course the ones I need ;-) ).
What can I do to diagnose, provide loggings etc?

**Comment by bartwybouw** [comment]
![Schermafbeelding 2020-05-24 om 11 21 36](https://user-images.githubusercontent.com/1301385/82750502-df09fc80-9db0-11ea-99e7-4505a83e61f5.jpg)
![Schermafbeelding 2020-05-24 om 11 20 45](https://user-images.githubusercontent.com/1301385/82750505-e0d3c000-9db0-11ea-86a0-a51e479b3ed9.jpg)
![Schermafbeelding 2020-05-24 om 11 20 30](https://user-images.githubusercontent.com/1301385/82750506-e16c5680-9db0-11ea-8502-ea522494a0b3.jpg)

**Comment by bartwybouw** [comment]
It seems out of my list of filaments, only one is useable.(rPLA RED)

**Comment by bartwybouw** [comment]
I think I've found the issue. 
It's not a bug, but it's confusing.

You have to make sure that the filament you want to use is selected in the tool box, and matches the one that you then select in the confirmation dialog.

For me it's more an issue of not guiding the user well enough, but not a bug.

So first, select the filament you want to use in the 'tool window' of Filament manager, then hit print and confirm the SAME filament in the confirmation pop-up.

IMHO, it would be better to allow the user to switch filament in that confirmation window, but make clear that you SWITCH to a different filament. Maybe add a button "change filament" ?

![Schermafbeelding 2020-05-24 om 11 34 47](https://user-images.githubusercontent.com/1301385/82750775-c1d62d80-9db2-11ea-9674-836c3a0ec33b.jpg)

**Comment by dzid26** [comment]
I was confused as well. I even anticipated that this is happening..., but couldn't find option in the settings to change filament. 
 - I forgot there was the little drop list on the bottom of the main screen.
- There should be the option to change filament in the confirmation window
