### ISSUE TITLE
Euro to USD & Filament Status in Print Status

### ISSUE THREAD

**Issue by CWRRT** [malnvenshorn/OctoPrint-FilamentManager#8]
Can you make an option to add $ instead of just Euro

Also, It would be nice to have a sidebar selector of some sort to select filament and have the print status box display the anticipated use/remaining.

**Comment by ikishk** [comment]
setting currency manually:
filamentmanager_spooldialog.jinja2
line 42

I second a "spool selector" on the sidebar.  having to go into the plugin settings each time seems tedious.

**Comment by malnvenshorn** [comment]
See #1 and #4.
