### ISSUE TITLE
[Request] Prusa MMU Support

### ISSUE THREAD

**Issue by bwright86** [malnvenshorn/OctoPrint-FilamentManager#84]
I just started using the Filament Manager plugin for Octoprint, and was trying to figure out how to setup Prusa's 4 extruder motors in the Filament manager. I currently only see 1 tool ("Tool 0") in the left navigation bar.

It would be helpful to be have a setting in the plugin that asks "How many extruders/motors does your printer have?", and then allow filaments to be assigned to each of the extruder motors. Whatever number is selected, that number of filament slots would be available in the left navigation bar.

The Prusa MMU feature utilizes the "T0, T1, T2, etc..." gcode to switch between the separate extruder motors. This could be detected to track which filament is being printed.
[Prusa Supported gcodes](https://github.com/prusa3d/Prusa-Firmware/wiki/Supported-G-codes)

This would be a helpful addition to the plugin.

**Comment by malnvenshorn** [comment]
The filament manager already supports multiple extruders. It reads the number you have configured in the printer profile octoprint uses.

**Comment by bwright86** [comment]
Yes, I was kind of assuming this was the case. For Prusa i3 MK2 MMU printers, it uses 1 real extruder w/ 4 extruder motors. In Octoprint, this is configured as 1 Extruder hotend, and then the gcode handles switching between (T0, T1, T2, etc...).

Not sure if you would want to allow this setting to be "overridden" in your plugin to allow for these extra extruders and to sniff the gcode for the T0, T1, T2, etc... commands to switch between them.

**Comment by malnvenshorn** [comment]
> For Prusa i3 MK2 MMU printers, it uses 1 real extruder w/ 4 extruder motors. In Octoprint, this is configured as 1 Extruder hotend [..]

Here is your mistake. In OctoPrint you configure this as 4 Extruders with the "Shared nozzle" flag set.

**Comment by bwright86** [comment]
Thank you, that actually was my issue. I was aware of the multi extruder setting, but i had never seen the "Shared Nozzle" setting, so OctoPrint was only detecting multiple tools when gcode was loaded and printed.

**Comment by tellison11232** [comment]
Thanks for your help so far, but I'm still having trouble setting this up. Is there a way to select the filament from OctoPrint? I'm trying to set up remote printing on the MK3 MMU2 and OctoPrint gets stuck because I need to select the filament by pushing the knob on the printer itself.
