### ISSUE TITLE
not counting when printing from sd

### ISSUE THREAD

**Issue by boelle** [malnvenshorn/OctoPrint-FilamentManager#9]
hi

i print a lot from sd as a pi can crash and is to slow

would it be possible to expand this so it can count if printing from sd?

**Comment by malnvenshorn** [comment]
No it's a limitation you have to live with. This plugin parses the commands which are send to the printer. If you put your gcode file on a sd card the commands will not be send through OctoPrint and it's not possible to parse them.

As a side note: I'm using a Raspberry Pi B+ myself and never had performance issues even with a webcam running.

**Comment by boelle** [comment]
oki... i will try that, but thanks anyway
